import { Note } from './notes';

export const mockNotes: Note[] = [
  {
    id: '1',
    category: 'Work',
    title: 'AI Product Launch Strategy',
    description: 'Planning our new AI-powered analytics dashboard. Key features: real-time sentiment analysis, predictive insights, custom ML models. Target launch: Q2 2026. Team assignments: Sarah (UI/UX), Marcus (ML pipeline), Lisa (API integration). Marketing angle: "Intelligence meets simplicity"',
    timestamp: '2 days ago',
    isFavorite: true,
  },
  {
    id: '2',
    category: 'Ideas',
    title: 'SaaS Startup Concept',
    description: 'Idea: A collaborative workspace for remote teams with AI meeting summaries, automatic task extraction, and smart scheduling. USP: Integrates with existing tools but adds intelligence layer. Revenue: Freemium + Enterprise. Competitors: Notion, Linear, but more AI-focused.',
    timestamp: '1 week ago',
    isFavorite: false,
  },
  {
    id: '3',
    category: 'Projects',
    title: 'Personal Portfolio Redesign',
    description: 'Rebuilding portfolio with Next.js 15, Framer Motion animations, and 3D elements using Three.js. Sections: Hero with interactive background, Projects showcase with case studies, Blog with MDX, Contact with email integration. Deploy on Vercel. Timeline: 3 weeks.',
    timestamp: '3 days ago',
    isFavorite: true,
  },
  {
    id: '4',
    category: 'Education',
    title: 'Learning Path: System Design',
    description: 'Week 1-2: Scalability fundamentals, Load balancing, Caching strategies. Week 3-4: Database sharding, CAP theorem, Microservices. Week 5-6: Message queues, CDNs, Real-world case studies (Netflix, Uber). Resources: Grokking System Design, ByteByteGo, Educative.io',
    timestamp: '5 days ago',
    isFavorite: false,
  },
  {
    id: '5',
    category: 'Personal',
    title: 'Morning Routine Optimization',
    description: '5:30 AM - Wake up, hydrate. 5:45 AM - 20 min meditation (Headspace). 6:05 AM - Cold shower. 6:15 AM - Protein smoothie + vitamins. 6:30 AM - Deep work session (no distractions). 8:00 AM - Gym or run. 9:00 AM - Start workday energized. Track progress weekly.',
    timestamp: '1 day ago',
    isFavorite: false,
  },
  {
    id: '6',
    category: 'Travel',
    title: 'Iceland Adventure 2026',
    description: 'Reykjavik (2 days): Blue Lagoon, Hallgrímskirkja, Northern Lights tour. Golden Circle (1 day): Þingvellir, Geysir, Gullfoss. South Coast (3 days): Seljalandsfoss, Skógafoss, Jökulsárlón glacier lagoon, Diamond Beach. Budget: $3500. Best time: September-October.',
    timestamp: '2 weeks ago',
    isFavorite: true,
  },
  {
    id: '7',
    category: 'Finance',
    title: 'Investment Strategy 2026',
    description: 'Portfolio allocation: 60% Index funds (VOO, VTI), 20% Tech stocks (NVDA, MSFT, GOOGL), 10% Crypto (BTC, ETH), 10% Bonds. Monthly DCA: $2000. Emergency fund: 6 months expenses. Long-term goal: Financial independence by 40. Review quarterly.',
    timestamp: '1 week ago',
    isFavorite: false,
  },
  {
    id: '8',
    category: 'Ideas',
    title: 'Side Hustle Ideas',
    description: '1. AI-powered content creation tool for marketers. 2. Notion templates marketplace. 3. Tech interview prep platform with mock interviews. 4. Freelance consulting: Web performance optimization. 5. YouTube channel: Coding tutorials + system design. Pick one, validate, execute.',
    timestamp: '4 days ago',
    isFavorite: false,
  },
  {
    id: '9',
    category: 'Projects',
    title: 'Open Source Contribution Plan',
    description: 'Target repos: Next.js, React, TailwindCSS. Start with good first issues, documentation improvements. Goals: 10 PRs merged by Q2, build reputation, network with maintainers. Time commitment: 5 hours/week. Benefits: Learning, visibility, giving back to community.',
    timestamp: '6 days ago',
    isFavorite: false,
  },
  {
    id: '10',
    category: 'Personal',
    title: 'Book Club Reading List',
    description: 'March: "Atomic Habits" by James Clear. April: "The Almanack of Naval Ravikant". May: "Deep Work" by Cal Newport. June: "Zero to One" by Peter Thiel. July: "The Mom Test" by Rob Fitzpatrick. Monthly discussions, key takeaways, action items.',
    timestamp: '3 days ago',
    isFavorite: true,
  }
];
